// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface ProductI {
  _id?: string;
  title: string;
  price: number;
  description: string;
  imgUrl?: string;
  stock: number;
  shopName?: string;
  shopId?: string;
  categoryName?: string;
  category: string;
}
