
// Generated by https://quicktype.io

export interface ProductI {
    _id?:         string;
    title:       string;
    imgUrl?:    string;
    price:       number;
    description: string;
    stock:       number;
    shopName?:    string;
    shopId?:      string;
    shop:{
        id:string,
        shopName: string,
    }
}
